---
# tasks file for nodejs

- set_fact:
    ansible_facts:
      pkg_mgr: yum

- name: Uninstall old java
  yum:
    name: java-1.7.0-openjdk
    state: absent

- name: Installing java, node, and npm
  yum:
    name: ['java-1.8.0', 'nodejs', 'npm']
    enablerepo: epel
    state: installed
